CREATE TABLE playlist_tracks (
 playlist_id INTEGER PRIMARY KEY AUTOINCREMENT,
 track_id TEXT NOT NULL, 
 FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE
 FOREIGN KEY (track_id) REFERENCES tracks(id) ON DELETE CASCADE
);
