-- Two users have signed up!
-- Write a SQL statement to add them to the database

-- [
--   {
--     firstName: 'Vincenza',
--     lastName: 'Kovacek',
--     email: 'Vincenza.Kovacek35@hotmail.com',
--     username: 'Vincenza.Kovacek',
--     password: 'oH_d5pqv7Ne0_Mc'
--   },
--   {
--     firstName: 'Lionel',
--     lastName: 'Ruecker',
--     email: 'Lionel.Ruecker@yahoo.com',
--     username: 'Lionel_Ruecker27',
--     password: '6CGHykGWEzFYRA_'
--   }
-- ]
